export const LOADEDPAGE = 'LOADEDPAGE';
export const LOADING = 'LOADING';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const FETCHED_SWAPI_TYPES_STARTED = 'search/FETCHED_SWAPI_TYPES_STARTED';
export const FETCHED_SWAPI_TYPES_SUCCESS = 'search/FETCHED_SWAPI_TYPES_SUCCESS';
export const FETCHED_SWAPI_TYPES_FAILED = 'search/FETCHED_SWAPI_TYPES_FAILED';
export const UPDATE_SEARCHER_TYPE = 'search/UPDATE_SEARCH_TYPE';
export const UPDATE_SEARCHER_QUERY = 'search/UPDATE_SEARCH_QUERY';

export const SEARCHED_SWAPI_STARTED = 'searchResults/SEARCHED_SWAPI_STARTED';
export const SEARCHED_SWAPI_SUCCESS = 'searchResults/SEARCHED_SWAPI_SUCCESS';
export const SEARCHED_SWAPI_FAILED = 'searchResults/SEARCHED_SWAPI_FAILED';

export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const UPDATE_SEARCH_TYPE = 'UPDATE_SEARCH_TYPE';
export const UPDATE_SEARCH_PARAMETERS = 'UPDATE_SEARCH_PARAMETERS';

export const HOME = 'HOME';
export const PEOPLE = 'PEOPLE';
export const PERSONAGE = 'PERSONAGE';
export const PLANETS = 'PLANETS';
export const FILMS = 'FILMS';
export const SPECIES = 'SPECIES';
export const VEHICLES = 'VEHICLES';
export const STARSHIPS = 'STARSHIPS';